### ISSUE TITLE
SyntaxError for Google Clasp v2.4.0

### ISSUE THREAD

**Issue by joshuanianji** [daikikatsuragawa/clasp-action#3]
Hey guys, thank you for this repo, it's been insanely useful.

When the action runs with the latest version of Clasp on GH Actions, it returns an error that seems to originate from a [bug in Clasp v2.4.0](https://github.com/google/clasp/issues/856#issuecomment-882016152).

```bash
/usr/lib/node_modules/@google/clasp/build/src/index.js:2
import why from 'wtfnode'; // should be your first require
       ^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

## Possible Solution:

This would be temporary, but using Clasp v2.3.2 should fix it until a patch is rolled out in the Clasp repo. I can file a PR if you would like!

**Comment by joshuanianji** [comment]
I tested using Google Clasp v2.3.2, and it seems to work for push commands. I'll file a PR if necessary.

Right now, I am using `joshuanianji/clasp-action@test`

**Comment by JarradPrice** [comment]
I updated the Dockerfile to use a newer alpine version and changed the syntax of the npm install to:
`apk add --update npm`
and got it working.

I created a pull request and in the meantime I am using `jarradprice/clasp-action@v1.0.1`

**Comment by daikikatsuragawa** [comment]
@joshuanianji @JarradPrice 

Thank you for opening Issue. Released with this content.

https://github.com/daikikatsuragawa/clasp-action/pull/4#issuecomment-905502636

**Comment by daikikatsuragawa** [comment]
@joshuanianji @JarradPrice
I will consider this issue resolved and close. Thank you!
